### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by Markus-Ende** [co-IT/schematics#12]
We should add integration tests that run schematics and check if the resulting file tree is correct.

## Resources

Example of how the Angular CLI itself does this can be found here: https://github.com/angular/angular-cli/tree/master/tests/legacy-cli/e2e

Other examples of integration tests of Angular:
https://github.com/angular/angular/tree/master/integration

Containing the bazel-schematics integration test:
https://github.com/angular/angular/blob/master/integration/bazel-schematics/test.sh

CLI e2e Tests
- https://medium.com/@zorrodg/integration-tests-on-node-js-cli-part-1-why-and-how-fa5b1ba552fe
- https://github.com/vesln/nixt

**Comment by Markus-Ende** [comment]
This is how kevinschuchard is doing this: https://www.kevinschuchard.com/blog/2018-11-20-schematic-sandbox/

**Comment by Markus-Ende** [comment]
Steps to manually test our schematics:
1. run `yarn link` from root folder
2. change to any other Angular project's root folder and run `yarn link @co-it/schematics`
3. Run `ng generate @co-it/schematics:commitlint` (or use any other schematic name) from within that test Angular project

**Comment by GregOnNet** [comment]
## Thoughts

- [ ] Generate new Angular project with the current version of the CLI
- [ ] Link built schematics into the generated project
- [ ] Specify which commands should be executed (A command can be the schematic command itself or an npm script)
  - Provide an API asserting the expected console output
  - Use Git to rollback the changes done by the command

**Comment by Markus-Ende** [comment]
I would like to add unit tests for the integration test utilities. But for this we have to decide about the project structure:
1. extract integration
