### ISSUE TITLE
jest setup fails in projects with multiple applications

### ISSUE THREAD

**Issue by GregOnNet** [co-IT/schematics#29]
## Problem

When a developer creates an Angular application executing `ng generate application my-app --minimal` the setup cannot resolve the project in `projects/my-app`.

## Error

```bash
ng g @co-it/schematics:jest
? Setup pre-push hook? Yes
No src/tsconfig.spec.json found
```

## Possible Solution

We should use [@angular-builders](https://github.com/meltedspark/angular-builders/tree/master/packages/jest).

## Further thoughts

An Angular application can be generated with `--minimal`. In this case, no test setup is done by the CLI.
We need to handle this case as well (create missing `tsconfig.spec.json`, etc.).

**Comment by Strulle** [comment]
I will provide a solution with the angular builder for jest 🙂

**Comment by GregOnNet** [comment]
Will be covered in #33.
