### ISSUE TITLE
ng g @co-it/schematics:commit-lint

### ISSUE THREAD

**Issue by GregOnNet** [co-IT/schematics#3]
- [x] Download `commitlint`
- [x] Register `commitlint` as pre-commit hook next to prettier & tslint
- [x] Create `commitlint` configuration file (❔not sure if there is a configuration)

**Comment by Markus-Ende** [comment]
Package name is [commitlint](https://github.com/conventional-changelog/commitlint), so I propose calling the schematic `@co-it/schematics:commitlint`.

**Comment by GregOnNet** [comment]
Right, I have updated the description.

**Comment by GregOnNet** [comment]
@Markus-Ende It seems that the template for commitlint was not added to the repository.

Can you please add it and send a new PR?

**Comment by Markus-Ende** [comment]
whaaat

**Comment by Markus-Ende** [comment]
It was ignored via .gitignore. See #7
