### ISSUE TITLE
ng g @co-it/schematics:cypress

### ISSUE THREAD

**Issue by GregOnNet** [co-IT/schematics#9]
- [x] Download cypress
- [x] Configure cypress to use TypeScript instantly
  - We may need to prepare the whole cypress directory
- [x] register command `cy:open` ➡️ `cypress open`
- [x] register command `cy:run` ➡️ `cypress run`

**Comment by Markus-Ende** [comment]
Content of the `/cypress` folder is created when running `cypress open` for the first time. But if there already is a `/cypress` folder with arbitrary content (like a tsconfig.json), it will still generate and add the default example files. 
So I think we could add typescript config files to `/cypress` folder without preparing the whole directory.

**Comment by Markus-Ende** [comment]
I successfully tried to setup cypress using the builder that is used in nx workspaces: https://github.com/Markus-Ende/angular-cypress-with-nrwl-builder

I would propose using this approach.

We could let the user provide the e2e app name to be replaced by Cypress as schematic parameter. Then we replace the content of this e2e folder with Cypress files and adjust angular.json entry for this e2e app.  In this way we are prepared for CLI workspaces with multiple projects.

**Comment by GregOnNet** [comment]
Sounds good so far.
We may wanna ask: `Overwrite protractor setup?`

If yes: Place cypress in `e2e/`
If no: Place cypress in `cypress/`

**Comment by GregOnNet** [comment]
Aah, now I got the idea with multiple projects.
What about an `--app` paramater.
The developer enters an existing app name.
Than we automatically produce `[app]-e2e`.

The app parameter allows us to get the path to the app from angular.json.

**Comment by GregOnNet** [comment]
How is your plan to implement the jest schematic?
I want to release the schematics this week.

In my opinion `cypress` is nice to have.
If we want to ship `cypress` with the first release we need to hurry a bit. :)

**Comment by Markus-Ende** [comment]
Starting right now :-)

Plan is to add a required `--app` parameter as you suggested. Then prompt the user if he wants to overwrite existing `[app]-e2e` project. If not, create a `[app]-cypress`.

**Comment by Markus-Ende** [comment]
## Parameters:
* `--app`: target app served for e2e tests. Default: `defaultProject` in `angular.json`
* `--folder`: install folder for cypress tests. Default: root folder of `[target app name]-e2e` entry in `angular.json`
* `--overwrite`: overwrite existing e2e folder? Default: false
 
## Scenarios:
**Scenario 1**: `ng g @co-it/schematics:cypress --overwrite=true`
1. read defaultProject from `angular.json`: `--app`= default-project-name
2. error, if no `[default-project-name]-e2e` entry in `angular.json` found
3. overwrite files in  `[default-project-name]-e2e` root folder

**Scenario 2**: `ng g @co-it/schematics:cypress --app=my-app`
1. error if my-app does not exist
2. search for `my-app-e2e` entry in `angular.json`
  a. exists: error, because `--overwrite` is false by default.
  b. does not exist: create `my-app-e2e` entry in `angular.json` with root according to root of `my-app` entry. Examples:
      `{"my-app": { "root": ""}}` --> `{"my-app-e2e": { "root": "my-app-e2e"}}`
      `{"my-app": { "root": "projects/my-app"}}` --> `{"my-app-e2e": { "root": "projects/my-app-e2e"}}`
      error, if root exists

**Scenario 3**: `ng g @co-it/schematics:cypress --app=my-app --folder=any/folder/cypress-tests`
resulting entry: `{"my-app-e2e": { "root": "any/folder/cypress-tests"}}`

**Comment by GregOnNet** [comment]
Hey @Markus-Ende,

### Port

after installing cypress and running `npm run e2e` the app is built and run on port **4200**. This means a developer needs to close the running server to be able to run cypress.

❓ Can we change the port?

### Cypress app closes

Running `npm run e2e` opens the cypress app. The app is immediately closed when the test run has finished.

A developer has no chance to debug if a test fails.
I think the command would also fail on a CI-Server since the Electron App is started.

❓ Can we provide two commands? 
- The first command opens the cypress app. The app keeps running after the tests have been executed
- The second command is intended to be run on a CI server.

### Sample test is red

When I run `npm run e2e` the predefined test is read since it checks if an h1-Tag contains _"Welcome to angular-cypress-with-nxbuilder!"_.

❓ Can we add a smoke test that will succeed no matter which app is tested?

**Comment by Markus-Ende** [comment]
>❓ Can we change the port?

I'll look into that


>❓ Can we provide two commands? 
> - The first command opens the cypress app. The app keeps running after the tests have been executed

This can be done with `ng e2e --watch`

> - The second command is intended to be run on a CI server.

This can be done with `ng e2e --headless`

Should I add npm scripts for that?

>❓ Can we add a smoke test that will succeed no matter which app is tested?

Sure, will do that!

**Comment by GregOnNet** [comment]
> This can be done with ng e2e --watch

Nice!
**We need to document it.**

> This can be done with ng e2e --headless
Nice!
**We need to document it.**

I do not think that we should predefine a script for the CI since it is possible to have multiple projects.

**Comment by GregOnNet** [comment]
@Markus-Ende 	

After thinking a bit about it I think it would be nice to provide a script `e2e:ci: ng e2e --headless`.
It will automatically run cypress for the default app and `--project <name>` can easily be passed to it. :)

**Comment by Markus-Ende** [comment]
@GregOnNet Actually it would run all e2e projects (if they all use the same builder; if not it will fail with an error message `Architect commands with command line overrides cannot target different builders.`)

Maybe we could add scripts per project? 
Like 
* `"e2e:my-app": "ng e2e --project=my-app-e2e"`
* `"e2e:watch:my-app": "ng e2e --watch --project=my-app-e2e"`
* `"e2e:ci:my-app": "ng e2e --headless --project=my-app-e2e"`

**Comment by GregOnNet** [comment]
Would be possible, but let us postpone this script-feature. :)

**Comment by GregOnNet** [comment]
@Markus-Ende Can we close this issue?

**Comment by Markus-Ende** [comment]
@GregOnNet yes I think so, currently it seems to be not possible to set the port. For the other things, I'll add documentation via #26 .
